name: 'Build for Deploy'
description: 'Release tag, Build Kotlin, Build Docker Image and Push'

inputs:
  image-suffix:
    required: false
    description: "Docker Image Name"

outputs:
  image:
    description: "Navnet på imaget som ble bygget"
    value: ${{ steps.docker-push.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: 'Assemble Kotlin'
      uses: ./actions/build-kotlin/action.yml
      with:
        task-type: 'assemble'

    # Disse trengs for å publisere arm64 docker image
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: nais/docker-build-push@v0
      id: docker-push
      with:
        team: teamdigisos
        tag: latest
        platforms: linux/amd64,linux/arm64/v8
        image_suffix: ${{ inputs.image-suffix }}
