name: 'Derive artifact version'
description: 'Derives artifact version from commit date and hash'

outputs:
  artifact-version:
    description: 'Artifact version from Commit'
    value: ${{ steps.create-artifact-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: 'Create artifact version from commit'
      id: create-artifact-version
      run: |
        date=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
        hash=$(git log -n 1 --pretty=format:'%h')
        echo "version=${date}_${hash}" >> $GITHUB_OUTPUT
      shell: bash
