name: 'Artifact Version from Commit'
description: 'Creates Artifact Version from Commit Date and Hash'

outputs:
  version:
    description: 'Artifact Version from Commit'
    value: ${{ steps.create-artifact-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: 'Create Artifact Version from Commit'
      id: create-artifact-version
      run: |
        date=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
        hash=$(git log -n 1 --pretty=format:'%h')
        echo "version=1.1_${date}_${hash}" >> $GITHUB_OUTPUT
      shell: bash
