name: "Build and push docker image"
description: "Login, build and push docker image to Github Docker Registry"
inputs:
  image-name:
    required: true
    description: Name for Image tags
  github-token:
    required: true
    description: Github Token for login

runs:
  using: "composite"
  steps:
    - name: Login to Github Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.github-token }}

    - name: Create docker image tags
      run: |
        echo "DOCKER_TAG=${{ inputs.image-name }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      shell: bash

    - name: Add latest tag
      if: github.ref == 'refs/heads/master'
      run: |
        echo "DOCKER_TAG=${{ env.DOCKER_TAG }} -t ${{ inputs.image-name }}:latest" >> $GITHUB_ENV
      shell: bash

    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_TAG }} .
      shell: bash

    - name: Push docker image
      run: docker push --all-tags ${{ inputs.image-name }}
      shell: bash