name: "Build and push docker image"
description: "Login, build and push docker image to Github Docker Registry"
inputs:
  image-name:
    required: true
    description: Name for Image tags
#  github-token:
#    required: true
#    description: Github Token

runs:
  using: "composite"
  steps:
    - name: Login to Github Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.github-token }}

    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_TAG }} .
      shell: bash

    - name: Push docker image
      run: docker push --all-tags ${{ inputs.image-name }}
      shell: bash