name: 'Build for Deploy'
description: 'Build Kotlin, Tag and Release, Build Docker Image and Deploy'

inputs:
  artifact-version:
    required: true
    description: 'Created version of this Artifact'
  image-name:
    required: false
    description: "Docker Image Name"
    default: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}

runs:
  using: 'composite'
  steps:
    - name: 'Create Tag and Release'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.artifact-version }}
        commit: ${{ github.sha }}
        allowUpdates: true

    - name: 'Assemble Kotlin'
      uses: navikt/sosialhjelp-ci/actions/functions/build-kotlin@v2
      with:
        task-type: 'assemble'

    - name: 'Build and Push Docker Image'
      uses: navikt/sosialhjelp-ci/actions/functions/build-and-push-docker-image@v2
      with:
        artifact-version: ${{ inputs.artifact-version }}
        image-name: ${{ inputs.image-name }}
