version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"

  - package-ecosystem: npm
    directory: actions/create-artifact-version/
    schedule:
      interval: daily
      day: monday
      time: "05:00"
    commit-message:
      prefix: "create-artifact-version"