name: "Build kotlin"
description: "Build kotlin, run lint and tests"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Run lint
      run: ./gradlew ktlintCheck
      shell: bash
    - name: Compile and run tests
      run: ./gradlew build
      shell: bash