name: "Build Image if Needed"
description: "Check if image tag exists, and build image if needed"
inputs:
  image-name:
    required: true
    description: 'Name for Image tags'
  github-token:
    required: true
    description: 'Github Token for login'
  artifact-version:
    required: true
    description: 'Created Artifact Version'
  build-image-always:
    required: false
    description: 'Build Image Always'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: 'Login to Github Docker Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: 'Docker Image Tag'
      run: |
        echo "DOCKER_TAG=${{ inputs.image-name }}:${{ inputs.artifact-version }}" >> $GITHUB_ENV
      shell: bash

    - name: 'Run docker manifest inspect'
      if: inputs.build-image-always == 'false'
      continue-on-error: true
      run: |
        docker manifest inspect ${{ env.DOCKER_TAG }} 2> IMAGE_OUTPUT
      shell: bash

    - name: 'Evaluate if image exists'
      if: inputs.build-image-always == 'false'
      run: |
        manifest=$(cat IMAGE_OUTPUT)
        echo "IMAGE_MANIFEST=$manifest" >> $GITHUB_ENV
      shell: bash

    - name: 'Build Image if Needed'
      if: env.IMAGE_MANIFEST == 'manifest unknown' || inputs.build-image-always == 'true'
      uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
      with:
        image-name: ${{ inputs.image-name }}
        github-token: ${{ inputs.github-token }}
        artifact-version: ${{ inputs.artifact-version }}
