name: "Build npm"
description: "Build npm project and run tests"

inputs:
  reader-token:
    required: true
    description: 'Reader token for installing dependencies'
  build-less:
    required: false
    description: 'Build less'
    default: 'false'
  run-orval:
    required: false
    description: 'Run orval'
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'
        cache: 'npm'
    - name: 'Install dependencies'
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.reader-token }}
      shell: bash
    - name: 'Run orval'
      if: inputs.run-orval != 'false'
      run: npm run orval
      shell: bash
    - name: 'Run tests'
      run: npm run test
      shell: bash
    - name: 'Build less'
      if: inputs.build-less != 'false'
      run: npm run build:css
      shell: bash
    - name: 'Build application'
      run: npm run build
      shell: bash