name: "Build npm"
description: "Build npm project and run tests"

inputs:
  reader-token:
    required: true
    description: 'Reader token for installing dependencies'
  build-less:
    required: false
    description: 'Build less'
    default: 'false'
  run-orval:
    required: false
    description: 'Run orval'
    default: 'false'
  node-version:
    description: "Node version to run on"
    required: false
    default: '18'
  build-css:
    description: "Toggle less build"
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.reader-token }}
      shell: bash

    - name: 'Run orval'
      if: ${{ inputs.run-orval == 'true' }}
      run: npm run orval
      shell: bash

    - name: 'Run tests'
      run: npm run test
      shell: bash

    - name: 'Build less'
      if: ${{ inputs.build-less == 'true' }}
      run: npm run build:css
      shell: bash

    - name: 'Build application'
      run: npm run build
      shell: bash
