version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      GOBIN: "/go/bin"
      CGO_ENABLED: 1
      APP_NAME_LINUX: "cistatus-linux"
      APP_NAME_MACOS: "cistatus-macos"
      APP_NAME_WINDOWS: "cistatus-windows.exe"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Install dependencies
          command: |
            sudo apt -y install libgl1-mesa-dev xorg-dev
            go get github.com/lucor/fyne-cross
      - run:
          name: Build application
          command: |
            cd cistatus
            go get .

            ./build.sh
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: "cistatus/release"
          destination: "cistatus"
