version: 2

jobs:
  build:
    docker:
      - image: dockercore/golang-cross:1.12.9
    environment:
      GOPATH: "/go"
      GOBIN: "/go/bin"
      CGO_ENABLED: 1
      APP_NAME_LINUX: "cistatus-linux"
      APP_NAME_MACOS: "cistatus-macos"
      APP_NAME_WINDOWS: "cistatus-windows.exe"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Install dependencies
          command: |
            apt -y install libgl1-mesa-dev xorg-dev
      - run:
          name: Build application
          command: |
            cd cistatus
            go get .

            env GOOS=linux GOARCH=amd64 go build -o "build/$APP_NAME_LINUX"
            # FIXME: 'X11/Xlib.h' and 'GL/glx.h' not found
            # env GOOS=linux GOARCH=amd64 CC=/osxcross/target/bin/o32-clang go build -o "build/$APP_NAME_MACOS"
            env GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -o "build/$APP_NAME_WINDOWS"
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: "cistatus/build"
          destination: "cistatus"
