name: "Build and push docker image"
description: "Build and push docker image to ghcr.io"
inputs:
  github-token:
    required: false
    description: 'Github Token for Login to Docker Reg.'
    default: 'false'
  artifact-version:
    required: true
    description: "Created Artifact Version"
  image-name:
    required: true
    description: 'Docker Image Name'

runs:
  using: "composite"
  steps:
    - name: 'Login to GitHub Docker Registry if GitHub Token Provided'
      if: ${{ inputs.github-token != 'false' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: 'Create docker image tags'
      run: |
        echo "DOCKER_TAG=${{ inputs.image-name }}:${{ inputs.artifact-version }}" >> $GITHUB_ENV
      shell: bash

    - name: 'Add latest tag'
      if: github.ref == 'refs/heads/master'
      run: |
        echo "DOCKER_TAG=${{ env.DOCKER_TAG }} -t ${{ inputs.image-name }}:latest" >> $GITHUB_ENV
      shell: bash

    - name: 'Build docker image'
      run: docker build -t ${{ env.DOCKER_TAG }} .
      shell: bash

    - name: 'Push docker image'
      run: docker push --all-tags ${{ inputs.image-name }}
      shell: bash
