name: "Build node"
description: "Build node project and run tests"

inputs:
  reader-token:
    required: false
    description: 'Reader token for installing dependencies'
  run-ci:
    required: false
    description: "Run pnpm ci"
    default: 'true'
  build-less:
    required: false
    description: 'Build less'
    default: 'false'
  run-orval:
    required: false
    description: 'Run orval'
    default: 'false'
  run-test:
    required: false
    description: 'Run npm test'
    default: 'true'
  node-version:
    required: false
    description: 'Node version'
    default: '18'
  pnpm-version:
    required: false
    description: 'Node version'
    default: '10'

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        cache: 'pnpm'

    - name: 'Install dependencies'
      if: ${{ inputs.run-ci == 'true' }}
      run: |
        pnpm i --prefer-offline
      env:
        NODE_AUTH_TOKEN: ${{ inputs.reader-token }}
      shell: bash

    - name: 'Run orval'
      if: ${{ inputs.run-orval == 'true' }}
      run: pnpm run orval
      shell: bash

    - name: 'Run tests'
      if: ${{ inputs.run-test == 'true' }}
      run: pnpm run test
      shell: bash

    - name: 'Build less'
      if: ${{ inputs.build-less == 'true' }}
      run: pnpm run build:css
      shell: bash

    - name: 'Build application'
      run: pnpm run build
      shell: bash
