name: Build and push docker image, tag and release

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: Name for Image tags
      artifact_name:
        required: false
        type: string
        description: Name for uploaded artifact
        default: app.jar

jobs:
  image:
    name: Build and push image -> tag and release
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ inputs.image_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master

      - name: Create docker image tags
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV

      - name: Add latest tag
        if: github.ref == 'refs/heads/master'
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }} -t ${{ env.DOCKER_IMAGE }}:latest" >> $GITHUB_ENV

      - name: Fetch jar file (download artifact)
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: build/libs

      - name: Build docker image
        run: docker build -t ${{ env.DOCKER_TAG }} .

      - name: Push docker image
        run: docker push --all-tags ${{ env.DOCKER_IMAGE }}

      - name: Create tag and release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.artifact-version.outputs.version }}
          commit: ${{ github.sha }}
