name: 'Remove Images from listed package names'
on:
  workflow_dispatch:

  schedule: ## Kjører kl. 05:00 mandag (schedule kjører bare for Default branch)
    - cron: '0 5 * * 1'

jobs:
  remove-images:
    name: 'Remove old images job except 50 most recent'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package-name:
          - sosialhjelp-soknad-api/sosialhjelp-soknad-api
          - sosialhjelp-soknad/sosialhjelp-soknad
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          min-versions-to-keep: 50
