name: 'Delete Images from List'
on:
  workflow_dispatch:

  schedule: ## Kjører kl. 05:00 mandag (schedule kjører bare for Default branch)
    - cron: '0 5 * * 1'

jobs:
  remove-images:
    name: Delete Old Images from ${{ matrix.package-name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package-name:
#          - sosialhjelp-soknad-api/sosialhjelp-soknad-api (privat repo pt.)
          - sosialhjelp-soknad/sosialhjelp-soknad
#          - sosialhjelp-innsyn-api/sosialhjelp-innsyn-api (privat repo pt.
          - sosialhjelp-innsyn/sosialhjelp-innsyn
          - sosialhjelp-modia/sosialhjelp-modia
          - sosialhjelp-modia-api/sosialhjelp-modia-api
          - sosialhjelp-adminpanel/sosialhjelp-adminpanel
          - sosialhjelp-avtaler/sosialhjelp-avtaler
          - sosialhjelp-avtaler-api/sosialhjelp-avtaler-api
          - digisos
          - sosialhjelp-mock-alt/sosialhjelp-mock-alt
          - sosialhjelp-kommune-service/sosialhjelp-kommune-service
          - sosialhjelp-fagsystem-mock/sosialhjelp-fagsystem-mock
          - sosialhjelp-mock-alt-api/sosialhjelp-mock-alt-api
          - sosialhjelp-login-api/sosialhjelp-login-api
          - sosialhjelp-soknad-api-db-migration/sosialhjelp-soknad-api-db-migration
          - sosialhjelp-test-proxy/sosialhjelp-test-proxy
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          min-versions-to-keep: 50
