  name: 'Deploy application'

  on:
    workflow_call:
      inputs:
        cluster-name:
          required: true
          type: string
          description: 'Deploy to which Cluster'
        resource-folder:
          required: false
          type: string
          description: 'Folder for K8s config'
          default: 'dev'

  jobs:
    build-for-deploy:
      name: 'Release Tag, Build artifact, Build and Push Image'
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: write
      outputs:
        docker-tag: ${{ steps.create-docker-tag.outputs.docker-tag }}
      env:
        DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
        ORG_GRADLE_PROJECT_githubUser: 'x-access-token'
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v3

        - name: 'Login to ghcr.io'
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Create Version from Commit'
          id: artifact-version
          uses: navikt/sosialhjelp-ci/actions/functions/simple-artifact-version@v2

        - name: 'Create Docker Image Tag'
          id: create-docker-tag
          run: |
            echo "docker-tag=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_OUTPUT

        - name: 'Check if Image Exists'
          id: inspect-image
          uses: navikt/sosialhjelp-ci/actions/functions/inspect-image@v2
          with:
            docker-tag: ${{ steps.create-docker-tag.outputs.docker-tag }}

        - name: 'If Needed - Release tag and Build Image'
          if: steps.inspect-image.outputs.image-manifest == 'manifest unknown'
          uses: navikt/sosialhjelp-ci/actions/components/build-for-deploy-kotlin@v2
          with:
            artifact-version: ${{ steps.artifact-version.outputs.version }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

    deploy-app:
      name: 'Deploy Application with NAIS Deploy'
      needs: build-for-deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Deploy to ${{ inputs.cluster-name }}
          uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            RESOURCE: nais/${{ inputs.resource-folder }}/${{ inputs.cluster-name }}.yaml
            CLUSTER: ${{ inputs.cluster-name }}
            REF: ${{ github.sha }}
            PRINT_PAYLOAD: true
            IMAGE: ${{ needs.build-for-deploy.outputs.docker-tag }}
