name: "Create and release tag"
description: "Creates and realeases tag"

outputs:
  artifact-version:
    description: Created artifact version
    value: ${{ steps.artifact-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Create artifact version
      id: artifact-version
      uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master

    - name: Create tag and release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.artifact-version.outputs.version }}
        commit: ${{ github.sha }}